spring:
    application:
        name: spring-tests
    datasource:
        url: jdbc:postgresql://${SPRING_TESTS_API_DATABASE_HOST}:${SPRING_TESTS_API_DATABASE_PORT}/${SPRING_TESTS_API_DATABASE_NAME}
        username: ${SPRING_TESTS_API_DATABASE_USERNAME}
        password: ${SPRING_TESTS_API_DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    liquibase:
        enabled: ${SPRING_TESTS_API_LIQUIBASE_ENABLED}
        change-log: classpath:db/changelog/master.xml

logging:
    level:
        org.springframework.security: trace