spring:
    application:
        name: spring-tests
    security:
        user:
            name: user
            password: password
        oauth2:
            authorizationserver:
                client:
                    oidc-client:
                        require-authorization-consent: true
                        registration:
                            client-id: "oidc-client"
                            client-secret: "{noop}secret"
                            client-authentication-methods:
                                - "client_secret_post"
                            authorization-grant-types:
                                - "authorization_code"
                                - "refresh_token"
                            redirect-uris:
                                - "http://localhost:4200/oauth2/callback"
                            post-logout-redirect-uris:
                                - "http://localhost:4200"
                            scopes:
                                - "openid"
                                - "profile"

logging:
    level:
        org.springframework.security: trace
